baseURL = "https://junoth.github.io"
languageCode = "zh-cn"
title = "Junoth"

theme = "canoe"

# last mod time support
enableGitInfo = true

# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage = true

[params]
  author = "Junoth"
  description = "Nihilist"
  copyright = "Copyleft@Junoth"
 # date format convert: http://fuckinggodateformat.com/
  dateFormat = "2006年01月_2日"
  # 用户头像地址, user avatar's url
  logo = "/img/avator.jpeg"
  
  # 首页横幅的背景链接, home banner's background url.
  splash_bg = "/img/bg.jpeg"

  # 是否使用一言, if using hitokoto(dynamic moto in splash screen)
  hitokoto =  false

  # 是否使用Canvas动态背景, if using canvas dynamic background (nest.js)
  nest_bg = true 

  # 是否使用动态加载效果, if using fade effect while loading (scroll-reveal.js)
  reveal_effect = true
  
# comment settings, support 'valine' and 'disqus'.
# more about 'valine', ref: http://valine.js.org/
[params.comment]
  type = "disqus" # or 'disqus'

[params.comment.valine]
  id = "< the appId >"
  key = "< the appKey >"
  placeholder = "< placeholder >"
  avatar = "retro"

[params.comment.disqus]
  shortname = '< short name >'


# Main menu
[[menu.main]]
    name = "Home"
    # associated with displaying order.
    weight = 1 
    url = "/"

[[menu.main]]
    name = "Archive"
    weight = 2
    url = "/archive/"
    
[[menu.main]]
    name = "About"
    weight = 6
    url = "/about/"



# 文章归类 Taxonomy
[[menu.taxonomy]]
  name = "Tag"
  identifier="tags"

[[menu.taxonomy]]
  name = "Category"
  identifier="categories"


# 社交账号 Social Network
[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-github'><use xlink:href='#svg-icons-github'></use></svg>"
  name = "Github"
  url = "https://github.com/junoth"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-twitter'><use xlink:href='#svg-icons-twitter'></use></svg>"
  name = "Twitter"
  url = "https://twitter.com/MiaoYuhang"


[blackfriday]
  extensions = ["laxHtmlBlocks","noEmptyLineBeforeBlock"]
